---
title: "Fundamentals of machine learning"
author: "joshna"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

---
```{r packages}
library(dplyr)
library(caret)
library(ISLR)
library(factoextra)
library(ggplot2)
```



```{r}
fuel_data<- read.csv("C:/Users/Joshn/Downloads/fuel_receipts_costs_eia923.csv",na.strings="")

colSums(is.na(fuel_data))
fuel_data<-fuel_data[,-c(3,7,12,13,19,20,21,22,23,24,25,26,27,28)]

colSums(is.na(fuel_data))

```


```{r clean}
set.seed(2312)
data2<-fuel_data %>% sample_frac(0.02)
index<-createDataPartition(data2$rowid,p=0.75,list=FALSE)

data2_Train<-data2[index,]
data2_Validation<-data2[-index,]


data2_Train<-na.omit(data2_Train)
data2_Validation<-na.omit(data2_Validation)
colSums(is.na(data2_Train))
colSums(is.na(data2_Validation))

data3_Train<-data2_Train[,c(9,12,13,14)]
data3_Validation<-data2_Validation[,c(9,12,13,14)]

set.seed(111)
norm_model<-preProcess(data3_Train, method = c("center", "scale"))

data3_train_norm<-predict(norm_model,data3_Train)
data3_Validation_norm<-predict(norm_model,data3_Validation)

```

```{r kmeans}
set.seed(1254)

fviz_nbclust(data3_train_norm[-1],kmeans,method='wss')
fviz_nbclust(data3_train_norm[-1],kmeans,method='silhouette')
```


```{r k}
set.seed(5467)
km<-kmeans(data3_train_norm[-1],centers=5,nstart = 25)
fviz_cluster(km,data=data3_train_norm[-1])
data3_Train$cluster<-as.factor(km$cluster)

ggplot(data3_Train)+geom_point(mapping=aes(x=data3_Train[,1],y=cluster,colour=cluster),position='jitter')+labs(title='K Means')
data3_Train%>%group_by(fuel_group_code)%>%summarise(mean_sulphur=mean(sulfur_content_pct),
                                            mean_ash=mean(ash_content_pct),
                                            avg_fuel_mmbtu_unit=mean(fuel_mmbtu_per_unit))%>%arrange(mean_sulphur)

data3_Train%>%group_by(cluster)%>%summarise(mean_sulphur=mean(sulfur_content_pct),
                                            mean_ash=mean(ash_content_pct),
                                            mean_fuel_mmbtu_unit=mean(fuel_mmbtu_per_unit))%>%
  arrange(mean_ash)
```

